# Generated by Django 5.2.1 on 2026-01-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aadhaar_no', models.CharField(max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('address', models.TextField()),
                ('police_station', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('TS', 'Telangana'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman & Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu'), ('JK', 'Jammu & Kashmir'), ('LD', 'Lakshadweep'), ('LA', 'Ladakh'), ('PY', 'Puducherry')], max_length=2)),
                ('course', models.CharField(choices=[('BTECH', 'B.Tech'), ('BE', 'B.E'), ('BCA', 'BCA'), ('BSC', 'B.Sc'), ('BCOM', 'B.Com'), ('BA', 'B.A'), ('BBA', 'BBA'), ('MTECH', 'M.Tech'), ('MCA', 'MCA'), ('MSC', 'M.Sc'), ('MCOM', 'M.Com'), ('MBA', 'MBA'), ('PHD', 'Ph.D'), ('DIPLOMA', 'Diploma'), ('CERT', 'Certificate')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
