# Generated by Django 5.2.1 on 2026-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admissionform_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
