# Generated by Django 5.2.1 on 2026-03-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_admissionform_father_name_admissionform_mother_name'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='aadhaar_no',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='district',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='state',
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='photo',
            field=models.ImageField(upload_to='admission_photos/'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
